"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { signInWithEmailAndPassword } from "firebase/auth";
import { auth } from "@/lib/firebase";
function friendlyError(code:string){if(code.includes("invalid-credential")||code.includes("wrong-password")||code.includes("user-not-found"))return "Email or password is incorrect.";if(code.includes("too-many-requests"))return "Too many attempts. Please wait and try again.";return "Unable to sign in right now. Please try again."}
export default function SignInPage(){
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const router=useRouter();
 async function submit(e:FormEvent){e.preventDefault();if(!auth){setMessage("Sign in is unavailable right now.");return}try{setBusy(true);setMessage("");const c=await signInWithEmailAndPassword(auth,email,password);router.push(c.user.emailVerified?"/get-started":"/verify-email")}catch(err){setMessage(friendlyError(err instanceof Error?err.message:""))}finally{setBusy(false)}}
 return <main><section className="page-hero"><div className="container"><span className="eyebrow">Welcome back</span><h1>Sign in securely.</h1><p className="lead">Continue your AutoFace profile, recommendations and introductions.</p></div></section><section className="section auth-polish-section"><div className="container auth-polish-layout"><form className="form" onSubmit={submit}><div className="field"><label>Email</label><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><div className="field-label-row"><label>Password</label><Link href="/forgot-password">Forgot password?</Link></div><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><button className="btn btn-primary" disabled={busy}>{busy?"Signing in…":"Sign in"}</button>{message&&<p className="notice notice-error">{message}</p>}<p className="muted">New to AutoFace? <Link href="/register"><b>Create account</b></Link></p></form><aside className="card auth-side-note"><span className="privacy-kicker">CONTROLLED BETA</span><h3>Your account remains under your control.</h3><p>After signing in you can manage Discovery participation, export AutoFace-held data and permanently delete your account.</p></aside></div></section></main>
}
