"use client";
import { FormEvent,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/AuthProvider";
import { relationshipIntentLabels,type RelationshipIntent } from "@/lib/profile";
import type { DiscoveryPreferences, ProfessionArea } from "@/lib/discovery-preferences";

export default function DiscoveryPreferencesPage(){
 const {user,loading}=useAuth();const router=useRouter();const [form,setForm]=useState<DiscoveryPreferences|null>(null);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{if(!loading&&!user)router.replace("/sign-in")},[loading,user,router]);
 useEffect(()=>{if(!user)return;const current=user;(async()=>{try{const token=await current.getIdToken();const r=await fetch("/api/discovery-preferences",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error??"Unable to load preferences.");setForm(b.preferences)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load preferences.")}})()},[user]);
 function toggleIntent(intent:RelationshipIntent){if(!form)return;const exists=form.relationshipIntents.includes(intent);setForm({...form,relationshipIntents:exists?form.relationshipIntents.filter(x=>x!==intent):[...form.relationshipIntents,intent]})}
 function toggleProfession(area:ProfessionArea){if(!form)return;const exists=form.preferredProfessionAreas.includes(area);setForm({...form,preferredProfessionAreas:exists?form.preferredProfessionAreas.filter(x=>x!==area):[...form.preferredProfessionAreas,area]})}
 async function save(e:FormEvent){e.preventDefault();if(!user||!form||saving)return;setSaving(true);setMessage("");try{const token=await user.getIdToken();const r=await fetch("/api/discovery-preferences",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(form)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error??"Unable to save preferences.");setMessage("Discovery preferences saved. Atlas will use them to choose the eligible pool before ranking recommendations.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to save preferences.")}finally{setSaving(false)}}
 if(loading||!user||!form)return <main><section className="section"><div className="container"><p className="muted">Loading discovery preferences…</p>{message&&<p className="notice">{message}</p>}</div></section></main>;
 return <main><section className="page-hero compact-hero"><div className="container"><span className="eyebrow">Discovery Preferences</span><h1>Control the recommendation pool.</h1><p className="lead">Preferences decide who is eligible to appear. Atlas compatibility then ranks those eligible members. Preferences do not change compatibility scores.</p></div></section>
 <section className="section"><div className="container preference-layout"><form className="card preference-form" onSubmit={save}><span className="privacy-kicker">HARD PREFERENCES</span><h2>Who should Atlas consider?</h2>
 <div className="preference-age"><label>Minimum age<input type="number" min={18} max={100} value={form.minAge} onChange={e=>setForm({...form,minAge:Number(e.target.value)})}/></label><span>to</span><label>Maximum age<input type="number" min={18} max={100} value={form.maxAge} onChange={e=>setForm({...form,maxAge:Number(e.target.value)})}/></label></div>
 <div className="field"><label>Location preference</label><select value={form.locationPreference} onChange={e=>setForm({...form,locationPreference:e.target.value as DiscoveryPreferences["locationPreference"]})}><option value="anywhere_uk">Anywhere in the UK</option><option value="same_general_area">Same general area as my profile</option></select><small>v0.12.1 uses the broad profile area only. AutoFace does not collect your precise location.</small></div>
 <div className="preference-block"><label>Relationship intention</label>{(Object.entries(relationshipIntentLabels) as [RelationshipIntent,string][]).map(([id,label])=><label className="toggle-row" key={id}><input type="checkbox" checked={form.relationshipIntents.includes(id)} onChange={()=>toggleIntent(id)}/><span><b>{label}</b></span></label>)}</div>
 <div className="preference-lifestyle card-inside">
   <span className="privacy-kicker">INTRODUCTION PREFERENCES</span><h3>What matters in an introduction?</h3>
   <p className="muted">Guidance rather than a checklist. These remain soft preferences in this release.</p>
   <div className="preference-two-col"><div className="field"><label>Preferred height from (cm)</label><input type="number" min="120" max="220" placeholder="No minimum" value={form.preferredHeightMinCm??""} onChange={e=>setForm({...form,preferredHeightMinCm:e.target.value?Number(e.target.value):null})}/></div><div className="field"><label>Preferred height to (cm)</label><input type="number" min="120" max="220" placeholder="No maximum" value={form.preferredHeightMaxCm??""} onChange={e=>setForm({...form,preferredHeightMaxCm:e.target.value?Number(e.target.value):null})}/></div></div>
   <div className="field"><label>How important is height?</label><select value={form.heightPreferenceImportance} onChange={e=>setForm({...form,heightPreferenceImportance:e.target.value as DiscoveryPreferences["heightPreferenceImportance"]})}><option value="doesnt_matter">Doesn&apos;t matter</option><option value="preference">Preference</option><option value="important">Important</option></select></div>
   <div className="field"><label>Location</label><select value={form.introductionLocation} onChange={e=>setForm({...form,introductionLocation:e.target.value as DiscoveryPreferences["introductionLocation"]})}><option value="doesnt_matter">Doesn&apos;t matter</option><option value="same_area">Same city / general area</option><option value="within_50_miles">Within roughly 50 miles</option><option value="uk_wide">UK-wide</option><option value="international">Open to international introductions</option></select></div>
   <div className="field"><label>Shared interests</label><select value={form.sharedInterestPreference} onChange={e=>setForm({...form,sharedInterestPreference:e.target.value as DiscoveryPreferences["sharedInterestPreference"]})}><option value="doesnt_matter">Doesn&apos;t matter</option><option value="preference">I&apos;d prefer some shared interests</option><option value="important">Shared interests are important</option></select></div>
   {form.sharedInterestPreference!=="doesnt_matter"&&<div className="preference-interest-grid">{[["fitness","🏋","Fitness"],["running","🏃","Running"],["sports","⚽","Sports"],["cinema","🎬","Cinema"],["travel","✈","Travel"],["food","🍽","Food"],["music","🎵","Music"],["reading","📚","Reading"],["gaming","🎮","Gaming"],["outdoors","🌳","Outdoors"],["socialising","☕","Socialising"],["nightlife","🎉","Nightlife"],["family","👨‍👩‍👧","Family time"],["volunteering","🤝","Volunteering"],["arts","🎨","Arts & culture"]].map(([value,icon,label])=><button type="button" key={value} className={`preference-interest-chip ${form.preferredSharedInterests.includes(value)?"selected":""}`} onClick={()=>setForm({...form,preferredSharedInterests:form.preferredSharedInterests.includes(value)?form.preferredSharedInterests.filter(x=>x!==value):[...form.preferredSharedInterests,value]})}><span>{icon}</span>{label}</button>)}</div>}
 </div>
  <div className="preference-career card-inside">
   <span className="privacy-kicker">CAREER & EDUCATION</span><h3>What professional background feels compatible?</h3>
   <p className="muted">These are soft preferences in v0.30.5. They help Atlas explain career fit but do not exclude an otherwise strong introduction.</p>
   <div className="field"><label>Profession preference</label><select value={form.professionPreferenceMode} onChange={e=>setForm({...form,professionPreferenceMode:e.target.value as DiscoveryPreferences["professionPreferenceMode"]})}><option value="doesnt_matter">Doesn&apos;t matter</option><option value="similar_outlook">Prefer a similar career outlook</option><option value="preferred_areas">I have preferred professional areas</option></select></div>
   {form.professionPreferenceMode==="preferred_areas"&&<div className="preference-profession-grid">{(["healthcare","technology","finance","engineering","education","legal","business","public_sector","creative","skilled_trades","other"] as ProfessionArea[]).map(area=><label className="toggle-row compact-toggle" key={area}><input type="checkbox" checked={form.preferredProfessionAreas.includes(area)} onChange={()=>toggleProfession(area)}/><span><b>{area==="public_sector"?"Public sector":area==="skilled_trades"?"Skilled trades":area.charAt(0).toUpperCase()+area.slice(1)}</b></span></label>)}</div>}
   <div className="field"><label>Education preference</label><select value={form.educationPreference} onChange={e=>setForm({...form,educationPreference:e.target.value as DiscoveryPreferences["educationPreference"]})}><option value="doesnt_matter">Doesn&apos;t matter</option><option value="similar_background">Similar educational background preferred</option><option value="graduate_preferred">Graduate preferred</option><option value="postgraduate_preferred">Postgraduate preferred</option></select></div>
 </div>
  <label className="toggle-row preference-relocation"><input type="checkbox" checked={form.requireRelocationOpen} onChange={e=>setForm({...form,requireRelocationOpen:e.target.checked})}/><span><b>Prefer people open to relocation</b><small>When enabled, candidates need a balanced-or-higher relocation flexibility answer in Atlas.</small></span></label>
 {message&&<p className="notice">{message}</p>}<button className="btn btn-primary" disabled={saving}>{saving?"Saving…":"Save preferences"}</button></form>
 <aside className="card preference-explainer"><span className="privacy-kicker">HOW IT WORKS</span><h3>Eligibility first. Ranking second.</h3><div className="recommendation-flow"><span>Safety + visibility</span><b>↓</b><span>Your preferences</span><b>↓</b><span>Eligible candidates</span><b>↓</b><span>Deterministic Atlas ranking</span><b>↓</b><span>Discover</span></div><p>AutoFace does not use popularity, likes, attractiveness or time-spent browsing to rank people.</p><a className="btn" href="/discover">Back to Discover</a></aside></div></section></main>
}
