import Link from "next/link";

const plans=[
{name:"AutoFace Free",price:"£0",cadence:"forever",eyebrow:"START HERE",description:"Build your profile and experience considered introductions without paying to be seen.",cta:"Create free account",href:"/register",features:["Member profile & profile photo","Atlas relationship profile","Core compatibility explanations","Limited considered recommendations","Mutual introductions & messaging","Core safety, blocking and privacy controls"]},
{name:"Founding Member",price:"£29",cadence:"one-off",eyebrow:"FOUNDING OFFER",featured:true,description:"Help establish the AutoFace community and receive the premium founding experience with permanent Founding Member status.",cta:"Join as a founding member",href:"/register",features:["Everything in AutoFace Free","Full Atlas explanations","Atlas Reflection","Advanced introduction preferences","Full recommendation history","Expanded considered introductions","Founding Member recognition","Permanent Founding Member status · no recurring subscription for the founding feature set"]},
{name:"AutoFace+",price:"£7.99",cadence:"per month",eyebrow:"PLANNED AFTER FOUNDING",description:"The planned ongoing membership for people who want the fuller Atlas and discovery experience.",cta:"Coming after founding",href:"/how-it-works",features:["Everything in AutoFace Free","Full Atlas experience","Advanced preferences","Expanded recommendation access","Full recommendation history","Additional future member insights"]}
];
const principles=[["Verification stays accessible","Core trust and safety should strengthen the whole community, not become a paywall."],["You cannot buy compatibility","Paying never increases your compatibility score or makes Atlas pretend someone is a better match."],["No pay-to-win visibility","AutoFace monetises useful capability, not artificial popularity or ranking tricks."]];
export default function PricingPage(){return <main><section className="pricing-hero"><div className="container pricing-hero-inner"><span className="eyebrow">Founding membership</span><h1>Help build AutoFace.<br/><span>Be there from the beginning.</span></h1><p className="lead">AutoFace is building its first community of verified members. Founding membership supports the product while giving early members access to the fuller AutoFace experience.</p><div className="pricing-beta-banner"><span>FIRST 500 VERIFIED MEMBERS</span><b>Founding Member · £29 one-off</b><small>Permanent Founding Member status · no recurring subscription for the founding feature set. Founding terms may evolve before general commercial launch.</small></div></div></section>
<section className="section pricing-section"><div className="container"><div className="pricing-grid">{plans.map(plan=><article className={`pricing-card ${plan.featured?"featured":""}`} key={plan.name}>{plan.featured&&<div className="pricing-popular">FOUNDING MEMBER</div>}<span className="privacy-kicker">{plan.eyebrow}</span><h2>{plan.name}</h2><p className="pricing-description">{plan.description}</p><div className="pricing-price"><strong>{plan.price}</strong><span>{plan.cadence}</span></div><Link className={`btn ${plan.featured?"btn-relationship":""}`} href={plan.href}>{plan.cta}</Link><div className="pricing-feature-list">{plan.features.map(f=><span key={f}><i>✓</i>{f}</span>)}</div></article>)}</div>
<div className="founding-callout card"><div><span className="privacy-kicker">WHY FOUNDING MEMBERS?</span><h2>Early members are helping create the community.</h2><p>A matching platform becomes more useful as the right community grows. The founding offer recognises people willing to join early, verify their profile, provide feedback and help AutoFace learn what genuinely matters.</p></div><div className="founding-number"><strong>500</strong><span>founding places planned</span></div></div>
<div className="pricing-principles"><div className="pricing-principles-head"><span className="privacy-kicker">THE AUTOFACE APPROACH</span><h2>Some things should never depend on what you pay.</h2><p>Revenue should fund a better product without undermining trust in Atlas or the authenticity model.</p></div><div className="pricing-principle-grid">{principles.map(([a,b])=><div className="pricing-principle" key={a}><span>✦</span><div><h3>{a}</h3><p>{b}</p></div></div>)}</div></div>
<div className="pricing-faq"><span className="privacy-kicker">EARLY COMMERCIAL MODEL</span><h2>Founding first. Subscription later.</h2><p>The £29 founding offer is the planned early-access commercial proposition. Payment processing is not enabled in v0.36; joining currently registers interest/access rather than taking payment.</p><div className="hero-actions"><Link className="btn btn-primary" href="/register">Create your profile</Link><Link className="btn" href="/feedback">Give feedback</Link></div></div></div></section></main>}
